In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()         
# After the loop release the cap object
cap.release()
# Destroy all the windows

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-06-24 00:20:25.619703: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-24 00:20:25.619815: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


2022-06-24 00:20:26.864318: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-06-24 00:20:27.096012: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 446ms/step
[[3.9233186e-05 3.1868232e-05 1.3655408e-05 9.9991524e-01]]
1/1 [==============================] - 0s 16ms/step
[[1.0269253e-03 2.3438003e-04 6.4195768e-04 9.9809676e-01]]
1/1 [==============================] - 0s 16ms/step
[[1.7874964e-04 5.8467165e-05 2.3989634e-04 9.9952281e-01]]
1/1 [==============================] - 0s 15ms/step
[[3.9490275e-04 1.6457084e-04 2.7339329e-04 9.9916708e-01]]
1/1 [==============================] - 0s 14ms/step
[[4.7162017e-03 1.1280928e-03 7.8940456e-04 9.9336630e-01]]
1/1 [==============================] - 0s 14ms/step
[[1.6095811e-03 5.3789123e-04 3.9975595e-04 9.9745268e-01]]
1/1 [==============================] - 0s 14ms/step
[[0.00811157 0.00238327 0.00135101 0.9881542 ]]
1/1 [==============================] - 0s 13ms/step
[[0.01023423 0.00721519 0.00840743 0.9741432 ]]
1/1 [==============================] - 0s 14ms/step
[[0.00367314 0.00270682 0.00204706 0.9915731 ]]
1/1 [======================

In [4]:
print(prediction[0][1])

0.032898918


: 